### ISSUE TITLE
Please add the dataset used in the code

### ISSUE THREAD

**Issue by umair-nasir14** [thsol/bidding-system#1]
Good day.

Hope you are doing great. It is to request that the dataset hasn't been uploaded and would be great if you can upload the dataset as the code will make more sense once we can see the data.

Thank you!

With kind regards.

**Comment by thsolomon** [comment]
Hi Umair, great to see you're interested in the project. Unfortunately, as this was a class room assignment we were specifically asked to not upload the test data.

**Comment by thsol** [comment]
Hi Umair, great to see you're interested in the project. Unfortunately, as this was a class room assignment we were specifically asked to not upload the test data.

**Comment by umair-nasir14** [comment]
Alright, thanks.
